### PR TITLE
Option to return password reset token without sending email

### PR DESCRIPTION
**Pull request by aitutaki**
As discussed in my email, FL want to send the password reset emails via the website so they require the reset token returning. Michael also asked for the user's _id property.

### CODE REVIEW

**Comment by Bochenski** [comment]
Hi Tom,

This opens up a security hole in that anyone can request this through the public api and receive a token - enabling them to hijack any account in the system.

Accordingly I cannot merge this PR.

What you'd need to do instead would be to create a separate API route to request a reset token for an e-mail, and make that api route admin only in routes.coffee

**Comment by aitutaki** [comment]
I realised after I sent the PR that the resetPassword route was public so thought you'd reject this based on that! I've not got around to creating the separate route and method but I'll try to do it shortly.


________________________________

**Comment by Bochenski** [comment]
No worries - glad to see you're keeping me on my toes in code review.  Just pop something similar on it's own admin wrapped route and it'll be fine.

**Comment by aitutaki** [comment]
Yep, will do.

________________________________

**Comment by aitutaki** [comment]
Sent another PR.

________________________________

**Pull request closed without merging**
